#!/bin/sh

# Composer
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

composer global require "laravel/installer=~1.1"

echo 'export PATH="$HOME/.composer/vendor/bin:$PATH"' >> ~/.bashrc && source ~/.bashrc

cp .env.example .env

composer install

php artisan key:generate

sudo chmod -R 777 storage

php artisan migrate:refresh

