#!/bin/sh

# http://tecadmin.net/install-php-7-nginx-mysql-on-ubuntu/

# PHP 7.0
sudo apt-get install python-software-properties
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo apt-get install -y php7.0 php7.0-fpm

# NGINX
sudo echo "deb http://nginx.org/packages/mainline/ubuntu/ `lsb_release -cs` nginx" >> /etc/apt/sources.list
sudo echo "deb-src http://nginx.org/packages/mainline/ubuntu/ `lsb_release -cs` nginx"  >> /etc/apt/sources.list

curl http://nginx.org/keys/nginx_signing.key | sudo apt-key add -
sudo apt-get update
sudo apt-get install nginx

# MySQL 5.6
sudo add-apt-repository -y ppa:ondrej/mysql-5.6
sudo apt-get update
sudo apt-get install mysql-server-5.6

# PHP Modules
sudo apt-cache search php7-*
sudo apt-get install php7.0-mysql php7.0-curl php7.0-json

# Composer
curl -sS https://getcomposer.org/installer | php
sudo mv composer.phar /usr/bin/composer

# Tips
echo "=================================================================================================="
echo "You need to un-comment cgi.fix_pathinfo=1 line in file /etc/php/7.0/fpm/php.ini and set value to 0."
echo "=================================================================================================="

echo "=================================================================================================="
echo "If you are using iptables, Use following commands to open port 80 for public access of webserver."
echo "Iptables Users: sudo iptables -A INPUT -m state --state NEW -p tcp --dport 80 -j ACCEPT"
echo "UFW Users: sudo ufw allow 80/tcp"
echo "=================================================================================================="
