#!/bin/sh

git checkout -- .

git pull

sudo chmod -R 755 ./
sudo chown -R www-data:www-data ./

#sudo chgrp -R www-data storage bootstrap/cache resources/lang public
sudo chmod -R ug+rwx storage bootstrap/cache resources/lang public

composer update
